apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: restaurant-demo
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "30"
    spec:
      containers:
        - image: docker.io/fukumame/k8s-restaurant-demo:1.0.0
          ports:
            - containerPort: 8000
          resources:
            requests:        # スケジューリング時に確保される最低限のリソース
              cpu: "100m"
              memory: "128Mi"
            limits:          # 使用量の上限。CPU は使用量が上限までに制限される（動作が遅くなるだけ）が、メモリは超えるとコンテナが強制終了される
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: MENU_NAME
              value: "KNative特製ランチ"
