apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulset
  namespace: default
spec:
  clusterIP: None  # Headless Serviceを指定
  selector:
    app: nginx-statefulset
  ports:
    - port: 80
      name: http
