apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secret
type: Opaque
data:
  SECRET_RECIPE: c2VjcmV0X3JlY2lwZV93aXRoX3NwZWNpYWxfc2F1Y2U=  # "secret_recipe_with_special_sauce" をBase64エンコード
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # "password123" をBase64エンコード
