apiVersion: v1
kind: Service
metadata:
  name: restaurant-service-clusterip
  labels:
    app: restaurant-demo
spec:
  type: ClusterIP
  selector:
    app: restaurant-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
