apiVersion: v1
kind: Service
metadata:
  name: restaurant-service-nodeport
  labels:
    app: restaurant-demo
spec:
  type: NodePort
  selector:
    app: restaurant-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # 30000-32767の範囲で指定可能（省略すると自動にポートが割り当てられる）
