apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-demo-deploy
  labels:
    app: restaurant-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-demo
  template:
    metadata:
      labels:
        app: restaurant-demo
    spec:
      containers:
        - name: restaurant-demo
          image: docker.io/fukumame/k8s-restaurant-demo:volume
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: recipe-storage
              mountPath: /app/recipes
      volumes:
        - name: recipe-storage
          persistentVolumeClaim:
            claimName: recipe-pvc
