apiVersion: v1
kind: Service
metadata:
  name: restaurant-service-loadbalancer
  labels:
    app: restaurant-demo
spec:
  type: LoadBalancer
  selector:
    app: restaurant-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
