apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: restaurant-demo-rs
  labels:
    app: restaurant-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restaurant-demo
  template:
    metadata:
      labels:
        app: restaurant-demo
    spec:
      containers:
        - name: restaurant-demo
          image: docker.io/fukumame/k8s-restaurant-demo:1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: MENU_NAME
              value: "焼き立てクロワッサン"
